// @include('../../node_modules/babel-polyfill/dist/polyfill.js')
// @include('../../node_modules/bowser/bowser.js')
// @include('../../node_modules/svg4everybody/dist/svg4everybody.js')
// @include('../../node_modules/jquery/dist/jquery.js')

// @include('../../node_modules/bootstrap/dist/js/bootstrap.bundle.js')
// @include('../../node_modules/bootstrap-select/js/bootstrap-select.js')
// @include('../../node_modules/bootstrap-select/js/i18n/defaults-ru_RU.js')
// @include('../../node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.js')
// @include('../../node_modules/bootstrap-datepicker/dist/locales/bootstrap-datepicker.ru.min.js')
// @include('../../node_modules/inputmask/dist/jquery.inputmask.js')
// @include('../../node_modules/slick-carousel/slick/slick.js')
// @include('../../node_modules/swiper/js/swiper.js')
